"""Prompt templates for LLM interactions."""
from .templates import (
    CLASSIFICATION_PROMPT,
    RESPONSE_GENERATION_PROMPT,
    KNOWLEDGE_RETRIEVAL_PROMPT,
    SENTIMENT_ANALYSIS_PROMPT,
    PRIORITY_ASSESSMENT_PROMPT,
    SUMMARY_PROMPT,
)

__all__ = [
    "CLASSIFICATION_PROMPT",
    "RESPONSE_GENERATION_PROMPT",
    "KNOWLEDGE_RETRIEVAL_PROMPT",
    "SENTIMENT_ANALYSIS_PROMPT",
    "PRIORITY_ASSESSMENT_PROMPT",
    "SUMMARY_PROMPT",
]
